/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.rygn.first_kafka.avro.domain;
@org.apache.avro.specific.AvroGenerated
public enum Kind implements org.apache.avro.generic.GenericEnumSymbol<Kind> {
  CAT, DOG, FISH  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Kind\",\"namespace\":\"org.rygn.first_kafka.avro.domain\",\"symbols\":[\"CAT\",\"DOG\",\"FISH\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
